Traceback (most recent call last):
  File "app.py", line 128, in <module>
    new_chromosomes_mutated, new_chromosomes_acc_mutated = mutate(new_chromosomes)
  File "app.py", line 110, in mutate
    fitness1 = fitness.getFitness(model1, epochs=2)
  File "/storage/research/un185/covid_min/fitness.py", line 11, in getFitness
    model.fit(x_train, y_train, epochs=epochs, verbose=verbose,validation_data=(x_test, y_test))
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.
